### ISSUE TITLE
Final pid file in pool is not written during restart

### ISSUE THREAD

**Issue by synth** [platanus/capistrano3-delayed-job#12]
In my app, we set the following dj capistrano variables in our config/deploy/production.rb

    set :delayed_job_workers, 4
    set :delayed_job_queues, ['priority', 'points', '*']
    set :delayed_job_pools, {
      'priority' => 1,
      'points' => 1,
      '*' => 2
    }

When we issue a cap production delayed_job:restart, what happens is that it stops all the jobs, and even starts them all up again, but the final delayed job process pid is not getting written. We end up with delayed_job.0.pid, delayed_job.1.pid, delayed_job.2.pid, but NOT delayed_job.3.pid. 

If I run directly on production:

    RAILS_ENV=production bin/delayed_job -n 4 --queues=priority,points,* --pool=priority:1 --pool=points:1 --pool=*:2 restart

it restarts all the processes and drops all the correct pid files, but I noticed that the final pid file is dropped after the program exits. See below.

````
[web@xxxx current]$ RAILS_ENV=production bin/delayed_job -n 4 --queues=priority,points,* --pool=priority:1 --pool=points:1 --pool=*:2 restart
delayed_job.0: trying to stop process with pid 30603...
delayed_job.0: process with pid 30603 successfully stopped.
delayed_job.1: trying to stop process with pid 30609...
delayed_job.0: process with pid 30683 started.
delayed_job.1: process with pid 30609 successfully stopped.
delayed_job.2: trying to stop process with pid 30615...
delayed_job.1: process with pid 30699 started.
delayed_job.2: process with pid 30615 successfully stopped.
delayed_job.3: trying to stop process with pid 30621...
delayed_job.2: process with pid 30715 started.
delayed_job.3: process with pid 30621 successfully stopped.
[web@xxxx current]$ delayed_job.3: process with pid 30728 started.

[web@xxxx current]$
````

So, it looks like there is some asynchronous behavior occurring. But why is the pid file not getting dropped when run under capistrano?

**Comment by dan-jensen** [comment]
I experienced this same issue, but for me it was less predictable.  With a larger number of workers, it seems PID files were missing at random.

For example, the following setting: 
```
set :delayed_job_workers, 8
```

Might produce only these PID files:
```
delayed_job.0.pid, delayed_job.1.pid, delayed_job.3.pid delayed_job.6.pid
```

I discovered this today when I started getting "ENOENT: No such file or directory @ rb_sysopen" errors from a job.  It turned out it was from one of these untracked Delayed Job processes that had survived 5+ Capistrano deployments.  This outdated process was looking for a file in a Capistrano release that was so old it didn't even exist on the server anymore.

SOLUTION:  It turns out the missing PID files are due to a bug with the Daemons gem.  It has been fixed in the master branch on GitHub (see the pull request at https://github.com/thuehlinger/daemons/pull/29).  Unfortunately the fix hasn't been published to the gem yet.  So until it is, you can use the following line in your Gemfile to use the code on GitHub:
```
gem 'daemons', github: 'thuehlinger/daemons'
```

**Comment by blackjid** [comment]
@synth does @dan-jensen solution (adding the latest daemons version) work for you?

do you think guys, that this is still an issue with this gem??

**Comment by dan-jensen** [comment]
I don't want to speak for @synth, but as far as I'm concerned this was an issue with the Daemons gem, so this issue can be closed.

**Comment by blackjid** [comment]
thanks!, I'll wait a bit for @synth ...

**Comment by synth** [comment]
I've reviewed the PR and yes it looks like this is the culprit. I won't be able to test with our app for a little while, but I feel confident we can go ahead and close this. I'll report back if anything crops up. Thanks @dan-jensen!

**Comment by blackjid** [comment]
:+1:
