### ISSUE TITLE
delayed jobs not being cleared up

### ISSUE THREAD

**Issue by phawk** [platanus/capistrano3-delayed-job#7]
Hey, I’m having an issue when deploying where the old delayed job processes aren’t being shut down when I deploy. I am not sure if this is an issue with how I am using the gem or an issue itself, maybe you could advise.

You run all tasks `within release_path` so the `bin/delayed_job ... restart` task for me just starts up new workers and leaves the old ones around. My configuration is like so:

```ruby
set :delayed_job_roles, [:worker]

set :delayed_job_pools, {
    :'tracking,feeds,mail,downloads,backup,tasks' => 2,
    :dropbox => 1
}
```

I was able to get the gem to work by adding this to the bottom of my `config/deploy.rb`

```ruby
after 'deploy:started', 'stop_delayed_job' do
  invoke 'delayed_job:stop'
end
```

**Comment by blackjid** [comment]
hey, I haven't being able to replicate the problem..

> You run all tasks within release_path so the bin/delayed_job ... restart task for me just starts up new workers and leaves the old ones around

If the problem is because we are running the `delayed_job` command from different releases, it should be possible to replicate that behaviour without capistrano. I tried starting delayed_jobs from a specific release (in the server without capistrano) and then running restart from a newer release, and the workers that went up are successfully restarted...

Any idea of what this could be ?? Could you try the same in you server? with the `pool` arguments??

```shell
## stop all workers

## then go to an old release, and start them
RAILS_ENV=production bin/delayed_job --pool=tracking,feeds,mail,downloads,backup,tasks:2 --pool=dropbox:1 start

## then go to a newer release an try with restart and see if all workers pid changes and if there are workers left behind.
RAILS_ENV=staging script/delayed_job --pool=tracking,feeds,mail,downloads,backup,tasks:2 --pool=dropbox:1 restart
```

**Comment by phawk** [comment]
@blackjid ah presuming this is because the pids for the process are in the `tmp` folder of rails app and this is checked into git, so it will have a different `tmp` folder per release

**Comment by blackjid** [comment]
ahp, maybe...
I have the `current/tmp` folder symlinked to the `shared/tmp`, so the tmp folder is the same for every release...

**Comment by phawk** [comment]
@blackjid yeah that makes more sense especially when it’s used to store pids and file cache etc. thanks for the help
